#!/usr/bin/env python3
"""Inject hardcoded release defaults into _config.py before building.

Run this script in the release pipeline AFTER tests and BEFORE ``python -m build``
to bake production connection defaults into the distributed package.

Required environment variables
--------------------------------
DUCKGRESQL_RELEASE_HOST          Production server hostname
DUCKGRESQL_RELEASE_FLIGHT_PORT   Arrow Flight SQL (gRPC) port
DUCKGRESQL_RELEASE_REST_PORT     REST API port

Optional environment variables
--------------------------------
DUCKGRESQL_RELEASE_USE_TLS       'true'/'false' (default: 'true')
DUCKGRESQL_RELEASE_REST_SCHEME   'http' or 'https' (default: 'https' when TLS enabled)

Usage
------
    python scripts/inject_release_defaults.py

After running, build normally:
    python -m build
"""

from __future__ import annotations

import os
import pathlib
import sys


def main(output_path: pathlib.Path | None = None) -> None:
    """Write a hardcoded _config.py.

    Parameters
    ----------
    output_path:
        Override the destination file (used in tests).  Defaults to the real
        ``src/duckgresql/_config.py`` relative to this script.
    """
    host = os.environ.get("DUCKGRESQL_RELEASE_HOST")
    flight_port_str = os.environ.get("DUCKGRESQL_RELEASE_FLIGHT_PORT")
    rest_port_str = os.environ.get("DUCKGRESQL_RELEASE_REST_PORT")

    missing = [
        name
        for name, val in [
            ("DUCKGRESQL_RELEASE_HOST", host),
            ("DUCKGRESQL_RELEASE_FLIGHT_PORT", flight_port_str),
            ("DUCKGRESQL_RELEASE_REST_PORT", rest_port_str),
        ]
        if not val
    ]
    if missing:
        print(
            f"Error: missing required environment variable(s): {', '.join(missing)}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Validated above — assert for type narrowing
    assert host and flight_port_str and rest_port_str

    flight_port = int(flight_port_str)
    rest_port = int(rest_port_str)

    use_tls_raw = os.environ.get("DUCKGRESQL_RELEASE_USE_TLS", "true").lower()
    use_tls = use_tls_raw in ("true", "1", "yes")

    default_scheme = "https" if use_tls else "http"
    rest_scheme = os.environ.get("DUCKGRESQL_RELEASE_REST_SCHEME", default_scheme)

    if output_path is None:
        output_path = (
            pathlib.Path(__file__).parent.parent / "src" / "duckgresql" / "_config.py"
        )

    content = (
        '"""Connection defaults — hardcoded at release time.\n\n'
        "This file is auto-generated by ``scripts/inject_release_defaults.py``.\n"
        "Do not edit manually.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        f"DEFAULT_HOST: str = {host!r}\n"
        f"DEFAULT_FLIGHT_PORT: int = {flight_port}\n"
        f"DEFAULT_REST_PORT: int = {rest_port}\n"
        f"DEFAULT_USE_TLS: bool = {use_tls}\n"
        f"DEFAULT_REST_SCHEME: str = {rest_scheme!r}\n"
    )

    output_path.write_text(content, encoding="utf-8")
    print(
        f"Injected release defaults into {output_path}:\n"
        f"  host={host!r}, flight_port={flight_port}, rest_port={rest_port}, "
        f"use_tls={use_tls}, rest_scheme={rest_scheme!r}"
    )


if __name__ == "__main__":
    main()
